name: jobo_app
description: JOBO Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  jobo_ui_kit:
    path: ../jobo_ui_lib
  flutter:
    sdk: flutter

  go_router: ^3.1.0
  flutter_riverpod: ^2.0.0-dev.7
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true
